name: Release Maven Project

on:
  push:
    tags:
      - 'v*.*.*'  # 监听所有版本标签

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build darwin
        run: mvn package -P darwin-aarch64

      - name: Build win
        run: mvn package -P win-amd64

      - name: Create GitHub release
        uses: gh-cli/gh-action@v1
        with:
          release-tag: ${{ github.ref }}
          release-title: "Release version ${{ github.ref }}"
          release-body: |
            Release notes go here...
          files: |
            target/*.jar
