name: Release Maven Project

on:
  push:
    tags:
      - 'v*.*.*'  # 监听所有版本标签

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build darwin
        run: mvn package -P darwin-aarch64

      - name: Build win
        run: mvn package -P win-amd64

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/hello-umiusi-*.zip

